Repository robbinjanssen/home-assistant-ojmicroline-thermostat, pull requests merged in 2024-02, with the labels that each got.

#127 Support WG4-series thermostats
  README.md
  custom_components/ojmicroline_thermostat/__init__.py
  custom_components/ojmicroline_thermostat/api.py
  custom_components/ojmicroline_thermostat/binary_sensor.py
  custom_components/ojmicroline_thermostat/climate.py
  custom_components/ojmicroline_thermostat/config_flow.py
  custom_components/ojmicroline_thermostat/const.py
  custom_components/ojmicroline_thermostat/coordinator.py
  custom_components/ojmicroline_thermostat/manifest.json
  custom_components/ojmicroline_thermostat/sensor.py
  custom_components/ojmicroline_thermostat/strings.json
  custom_components/ojmicroline_thermostat/translations/en.json
  poetry.lock
  pyproject.toml
Labels: new-feature

#134 Update pt.json
  custom_components/ojmicroline_thermostat/translations/pt.json
Labels: enhancement

#141 Fixes: unexpected keyword argument 'hvac_mode'
  custom_components/ojmicroline_thermostat/climate.py
Labels: bugfix

#143 Refactor thermostat modes & actions
  custom_components/ojmicroline_thermostat/climate.py
  custom_components/ojmicroline_thermostat/const.py
  custom_components/ojmicroline_thermostat/icons.json
  custom_components/ojmicroline_thermostat/strings.json
  custom_components/ojmicroline_thermostat/translations/en.json
Labels: enhancement

#144 Tweak sensor date handling
  custom_components/ojmicroline_thermostat/sensor.py
Labels: enhancement

#145 Add Dutch and Portuguese translations for climate entity
  custom_components/ojmicroline_thermostat/translations/nl.json
  custom_components/ojmicroline_thermostat/translations/pt.json
Labels: enhancement
